version: '3.8'

services:
  mosquitto:
    build: ./mosquitto
    container_name: mosquitto
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/aclfile:/mosquitto/config/aclfile
      - ./data:/encrypted
    restart: unless-stopped
    entrypoint: /entrypoint.sh
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse
    environment:
      # TODO: Adjust as neeed (but not here!)
      ENCFS_PASSWORD: your_secure_password_here

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    environment:
      - CLOUDFLARE_TUNNEL_TOKEN
