name: CI

on:
  push:
  pull_request:

jobs:
  test-mosquitto:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Mosquitto service using Docker Compose
        run: docker-compose up -d mosquitto

      - name: Wait for Mosquitto to be healthy
        run: |
          for i in {1..10}; do
            STATUS=$(docker inspect --format='{{.State.Status}}' mosquitto)
            if [ "$STATUS" = "running" ]; then
              echo "Mosquitto container is running"
              if docker exec mosquitto mosquitto_pub -t test/topic -m "health check" -r; then
                echo "Mosquitto is ready"
                break
              else
                echo "Mosquitto is not ready yet, retrying..."
                sleep 10
              fi
            elif [ "$STATUS" = "restarting" ]; then
              echo "Mosquitto container is restarting"
              sleep 10
            else
              echo "Mosquitto container is in unexpected state: $STATUS"
              docker logs mosquitto
              exit 1
            fi
          done

      - name: Publish a retained message to Mosquitto
        run: docker exec mosquitto mosquitto_pub -t test/topic -m "Test message" -r

      - name: Stop Mosquitto service using Docker Compose
        run: docker-compose down

      - name: Check encrypted data
        run: |
          docker run --rm -v $(pwd)/data:/encrypted alpine:latest /bin/sh -c 'if [ $(ls /encrypted | wc -l) -gt 1 ]; then echo "Data is encrypted"; else echo "Data is not encrypted"; exit 1; fi'
