name: CI

on:
  push:
  pull_request:

jobs:
  test-mosquitto:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Mosquitto service using Docker Compose
        run: docker-compose up -d mosquitto

      - name: Wait for Mosquitto to be healthy
        run: |
          for i in {1..10}; do
            if [ "$(docker inspect --format='{{.State.Health.Status}}' mosquitto)" = "healthy" ]; then
              echo "Mosquitto is healthy"
              break
            else
              echo "Waiting for Mosquitto to be healthy..."
              sleep 10
            fi
          done

      - name: Publish a retained message to Mosquitto
        run: docker exec mosquitto mosquitto_pub -t test/topic -m "Test message" -r

      - name: Stop Mosquitto service using Docker Compose
        run: docker-compose down

      - name: Check encrypted data
        run: |
          docker run --rm -v $(pwd)/data:/encrypted alpine:latest /bin/sh -c 'if [ $(ls /encrypted | wc -l) -gt 1 ]; then echo "Data is encrypted"; else echo "Data is not encrypted"; exit 1; fi'
